r189: Major rewrite.

diff --git a/drbd/scripts/drbd b/drbd/scripts/drbd
--- a/drbd/scripts/drbd
+++ b/drbd/scripts/drbd
@@ -13,115 +13,100 @@
 # Some ideas and inspiration from Joe Hartley <jh@brainiac.com>
 
 # Source function library.
-# Some distributions don't have it, so test and act accordingly
 
-INSTALL="/etc/ha.d/resource.d"
-. $INSTALL/drbd_commun
+export INSTALL="/etc/ha.d/resource.d"
+. $INSTALL/drbd_commun $*
 
-# Source networking configuration.
-if [ -f /etc/sysconfig/network ]; then
-	. /etc/sysconfig/network
-	# Check that networking is up.
-	if [ "$NETWORKING" = "no" ]; then
-		echo drbd: networking is down!
-		exit 1
-	fi
-fi
 # If the distribution does not have sysconfig/network, let's hope
 # networking is up.
+# TM : I don't like to hope stop if not here . Will add distro specif code.
 
-# Check for drbdsetup
-if [ ! -x /usr/sbin/drbdsetup ]; then
-	echo drbd: drbdsetup not found!
+have_file /etc/sysconfig/network
+
+if [ "$NETWORKING" = "no" ]; then
+	echo "$0 : The network is not accessible"
 	exit 1
 fi
 
 # Check for drbd's module
 if [ ! -f /lib/modules/`uname -r`/block/drbd.o ]; then
-	echo drbd: module not found!
+	echo "$0 : module not found. did you upgraded your kernel ?"
 	exit 1
 fi
-
-# Check for our config directory
-if [ ! -d $CONFIG ]; then
-	echo drbd: configuration directory not found!
-	exit 1
-fi
-
-cd $CONFIG
-DEVICES=`ls drbd[0-9] 2>/dev/null`
-
-# RETVAL will work as a "stuck bit" for any error. The construct
-# RV=$?
-# [ $RETVAL -eq 0 ] && RETVAL=$RV
-# allows us to have it stuck at 1 when some error occur, even if
-# subsequent operations don't fail. Using $RV prevents us from getting
-# the exit value of [ ... ]. That was a dumb one... :)
-RETVAL=0	# this means there were errors
-RV=0		# this means there were errors in the current device
-MINOR_COUNT=`echo $DEVICES | wc --words | sed -e s/\ //g`
 
 # See how we were called.
 case "$1" in
-  start)
-  	# use -s in modprobe/rmmod to keep errors in the logs
-	action "Loading DRBD module" /sbin/modprobe -s drbd \
-            minor_count=$MINOR_COUNT
-	[ $? -ne 0 ] && exit 1
+	# Start the service
+	start)
+		MINOR_COUNT=`echo $DEVICES | wc --words | sed -e s/\ //g`
+		action "Loading DRBD module " modprobe -s drbd minor_count=$MINOR_COUNT 2> /dev/null
 
-	for D in $DEVICES; do
-	    . $D
+		if [ $? -eq 1 ]; then
+			exit 1
+		fi
 
-		setLocal
+		if [ -z "$RESOURCE" ]; then
+			runForAll configure
+			exit $RETVAL
+		else
+			$0 configure $RESOURCE
+		fi
 
-		action "Configuring DRBD resource $D" \
-		    /usr/sbin/drbdsetup $LOCAL_DEVICE $LOCAL_PARTITION \
-	    $PROTOCOL $LOCAL_IF $REMOTE_IF $OPTIONS 
+		;;
+
+	# internal start sub function
+	configure)
+		setLocal $CONFIG $RESOURCE
+
+		have_device $RESOURCE
+
+		action "Configuring DRBD resource $RESOURCE" \
+			drbdsetup $LOCAL_DEVICE $LOCAL_PARTITION \
+			$PROTOCOL $LOCAL_IF $REMOTE_IF $OPTIONS 2> /dev/null
+
 		RV=$?
 		[ $RETVAL -eq 0 ] && RETVAL=$RV
 
-	    isMasterBoot $D 
-	    if [ ! $? ]; then
+		isMasterBoot $RESOURCE
+		if [ ! $? ]; then
 			if [ $RV -eq 0 ]; then
-			echo -n "Waiting for drdb to initialize (Can not fail)"
-			sleep 30
-			success
-			
-			# don't wait if there was an error in this device
-			action "Waiting for DRBD resource $D to resynchronize" \
-			    /usr/sbin/drbdsetup $LOCAL_DEVICE WAIT
-		else
-			succed "Node is master nothing to sync"
+				echo -n "Connection to master in 10 seconds"
+				sleep 10
+				success
+
+				action "resynchronizing resource $RESOURCE" \
+					drbdsetup $LOCAL_DEVICE WAIT
+			else
+					succed "Node is slave nothing to sync"
+			fi
 		fi
-	     fi
-	done
-	;;
+		;;
+
+	stop)
+		INSERTED=`lsmod | grep drbd | wc -l`
+
+		if [ "$INSERTED" -eq 1 ]; then
+			action "Unloading DRBD module" rmmod -s drbd
+			RETVAL=$?
+		else
+			succed "DRBD module was not loaded"
+		fi
+		;;
+
+	restart)
+		$0 stop
+		$0 start
+		RETVAL=$?
+		;;
 	
-  stop)
-	action "Unloading DRBD module" /sbin/rmmod -s drbd
-	RETVAL=$?
-	;;
-	
-  restart)
-	$0 stop
-	$0 start
-	RETVAL=$?
-	;;
-	
-  status)
-  	# Duplicated code from drbdc
-	if [ -r /proc/drbd ]; then
-		cat /proc/drbd
-	else
-		echo "DRBD module not loaded."
+	status)
+		$INSTALL/drbdc proc
+		RETVAL=$?
+		;;
+	*)
+		echo "Usage: $0 {start|stop|restart|status}"
 		RETVAL=1
-	fi
-	;;
-	
-  *)
-	echo "Usage: $0 {start|stop|restart|status}"
-	RETVAL=1
-	;;
+		;;
 esac
 
 exit $RETVAL
diff --git a/drbd/scripts/drbd_commun b/drbd/scripts/drbd_commun
--- a/drbd/scripts/drbd_commun
+++ b/drbd/scripts/drbd_commun
@@ -1,25 +1,13 @@
 #!/bin/sh
 
+# Commun function to all drbd script
 # Copyright (C) 2000, Thomas Mangin <thomas.mangin@free.fr>
-# bug fixing Dan Yocum, <yocum@linuxcare.com>
+# This file is under the GPL licence
+# Thank you to Dan Yocum, <yocum@linuxcare.com> for is help bug fixing
 
 HOST=`hostname -s`
 CONFIG="/etc/sysconfig/drbd"
 STATE="/var/lib/drbd"
-
-# RETVAL will work as a "stuck bit" for any error. The construct
-# RV=$?
-# [ $RETVAL -eq 0 ] && RETVAL=$RV
-# allows us to have it stuck at 1 when some error occur, even if
-# subsequent operations don't fail. Using $RV prevents us from getting
-# the exit value of [ ... ]. That was a dumb one... :)
-
-RETVAL=0    # this means there were no errors
-RV=0        # in this script this is just a temporary variable
-if [ $# -eq 2 ]; then
-	RESOURCE=$1
-    shift
-fi
 
 # Source function library.
 # Some distributions don't have it, so test and act accordingly
@@ -27,8 +15,8 @@ fi
 if [ -f /etc/rc.d/init.d/functions ]; then
 	result=`grep success /etc/rc.d/init.d/functions`
 	if [ $? ]; then
-			. /etc/rc.d/init.d/functions
-			HAVE_SUCCESS=1
+		. /etc/rc.d/init.d/functions
+		HAVE_SUCCESS=1
 	fi
 fi
 
@@ -80,6 +68,72 @@ action()
 	fi
 }
 
+# /proc analysis
+
+# Check if the node is primary
+# Param : The resource
+# Return "1" or "0"
+isPrimary()
+{
+	NUMBER=`echo $1 | cut -b5`
+	return `cat /proc/drbd | grep ":Primary/" | grep "^$NUMBER" | wc -l | cut -b7`
+}
+
+# Check if the other node is primary
+# Param : The resource
+# Return "1" or "0"
+haveRemotePrimary()
+{
+	NUMBER=`echo $1 | cut -b5`
+	return `cat /proc/drbd | grep "/Primary" | grep "^$NUMBER" | wc -l | cut -b7`
+}
+
+# Check if the other node is slave
+# Param : The resource
+# Return "1" or "0"
+haveRemoteSecondary()
+{
+	NUMBER=`echo $1 | cut -b5`
+	return `cat /proc/drbd | grep "/Secondary" | grep "^$NUMBER" | wc -l | cut -b7`
+}
+
+# Check if the node is in a connected state
+# Param : The resource
+# Return "1" or "0"
+isConnected()
+{
+	NUMBER=`echo $1 | cut -b5`
+	return `cat /proc/drbd | grep "Connected" | grep "^$NUMBER" | wc -l | cut -b7`
+}
+
+# Check if the node is in the process of full syncing
+# Param : The resource
+# Return "1" or "0"
+isSyncing()
+{
+        NUMBER=`echo $1 | cut -b5`
+        return `cat /proc/drbd | grep "Syncing" | grep "^$NUMBER" | wc -l | cut -b7`
+}
+
+
+# Check if the node is a working slave
+# Param : The resource
+# Return "1" or "0"
+isWorkingSecondary()
+{
+	NUMBER=`echo $1 | cut -b5`
+	return `cat /proc/drbd | grep "Connected" | grep "^$NUMBER" | grep "Secondary/" | wc -l | cut -b7`
+}
+
+# Check if the node is a working master
+# Param : The resource
+# Return "1" or "0"
+isWorkingPrimary()
+{
+	NUMBER=`echo $1 | cut -b5`
+	return `cat /proc/drbd | grep "Connected" | grep "^$NUMBER" | grep "Primary/" | wc -l | cut -b7`
+}
+
 # Boot state check/set
 
 isMasterBoot()
@@ -117,59 +171,169 @@ range()
 # Information grabbing
 
 # set LOCAL_DEVICE : set environement value with the node configuration info
-# $1 RESOURCE FILE
+# $1 RESOURCE DIRECTORY
+# $2 RESOURCE FILE
 setLocal()
 {
+	# This setup the local configuration variable for the local computer
+
+	. $1/$2
+
 	LOCAL_DEVICE=""
 	LOCAL_FSCK=""
 
-	host_line=`grep _HOST $CONFIG/$1 | grep $HOST`
-	node=`echo $host_line | cut -f1 -d"_" | cut -f2 -d"E"`
+	# This part of the code is N node safe
 
-	for line in `cat $CONFIG/$1`
+	HOST_NAMES=`grep _HOST $CONFIG/$2 | grep $HOST`
+	LOCAL_NUMBER=`echo $HOST_NAMES | cut -f1 -d"_" | cut -f2 -d"E"`
+
+	if [ "$LOCAL_NUMBER" = "" ]; then
+		failed "The configuration file don't define this host"
+		exit 1
+	fi
+
+	for LINE in `cat $1/$2 | sed -e"s/ /#/g" | grep -v "^#"`
 	do
-		keep=`echo $line | grep ^[nN][oO][dD][eE]$node | wc -l`
-		if [ "$keep" -eq 1 ]; then
-		 	affectation=`echo $line | sed -e"s/NODE$node/LOCAL/g"`
-			name=`echo $affectation | cut -f1 -d"="`
-			value=`echo $affectation | cut -f2 -d"="`
-			echo $affectation
-			echo set $name $value
-			set $name $value
+		KEEP=`echo $LINE | grep ^[nN][oO][dD][eE]$LOCAL_NUMBER | wc -l`
+		if [ "$KEEP" -eq 1 ]; then
+		 	VALUE=`echo $LINE | sed -e"s/[nN][oO][dD][eE]$LOCAL_NUMBER/LOCAL/g" | sed -e"s/#/ /g"`
+			eval $VALUE
+		fi
+
+		KEEP=`echo $LINE | grep "^[gG][lL][oO][bB][aA][lL]" | wc -l`
+		if [ "$KEEP" -eq 1 ]; then
+			VALUE=`echo $LINE | sed -e"s/[gG][lL][oO][bB][aA][lL]_//g" | sed -e"s/#/ /g"`
+			eval $VALUE
+		fi
+	done
+
+	# TODO: In a configuration with more than two nodes, drdbsetup syntax
+	# is not nice as you have several "REMOTE_IF" parameter to catch.
+
+	# This part of the code is only working with TWO nodes
+
+	for LINE in `cat $1/$2 | sed -e"s/ /#/g" | grep -v "^#"`
+	do
+		KEEP=`echo $LINE | grep "^[nN][oO][dD][eE]" | grep -v "^[nN][oO][dD][eE]$LOCAL_NUMBER" | grep "_IF" | wc -l`
+
+		if [ "$KEEP" -eq 1 ]; then
+			REMOTE_NUMBER=`echo $LINE | cut -f1 -d"_" | cut -f2 -d"E"`
+			VALUE=`echo $LINE | sed -e"s/[nN][oO][dD][eE]$REMOTE_NUMBER/REMOTE/g" | sed -e"s/#/ /g"`
+			eval $VALUE
 		fi
 	done
 }
 
-echo xxxxxx
-setLocal drbd.example
-echo xxxxxx
-set
-echo xxxxxx
+runForAll ()
+{
+	pushd . > /dev/null
+		cd $CONFIG
+		DEVICES=`ls drbd[0-9] | sort 2>/dev/null`
+	popd > /dev/null
 
+	if [ ! $DEVICES ]; then
+		failed "No configuration file present"
+		exit 1
+	fi
+
+	for DEVICE in $DEVICES; do
+		for RUN in $*; do
+			$0 $RUN $DEVICE
+		done
+	done
+}
+
+# Check if a environment value is set
+# $1 Name
+# $2 Value
+have_env()
+{
+	if [ ! $2 ]; then
+		echo "This script is not programmed to be used standalone"
+		failed "$0 needs the environment value '$1'"
+		exit 1
+	fi
+}
+
+
+# Check the presence of a directory
+# $* Directories to find
+have_dir()
+{
+	for NAME in $*
+	do
+		if [ ! -d $NAME ]; then
+			failed "$0 needs the configuration directory '$NAME'"
+			exit 1
+		fi
+	done
+}
+
+# Check the presence of a file
+# $* files check
+have_file()
+{
+	for NAME in $*
+	do
+		if [ ! -f $NAME ]; then
+			failed "$0 need the file '$NAME'"
+			exit 1
+		fi
+	done
+}
+
+# Check the presence in the path of an application
+# $* commands without path
+have_command()
+{
+	for NAME in $*
+	do
+		if [ ! `which $NAME 2>/dev/null` ]; then
+			failed "$0 needs the command '$NAME'"
+			exit 1
+		fi
+	done
+}
+
+# Check the presence in the path of an application
+# $* the device name
+have_device()
+{
+	for NAME in $*
+	do
+		if [ ! -b /dev/$NAME ]; then
+			failed "$0 needs the device '/dev/$NAME'"
+			exit 1
+		fi
+	done
+}
+
+# Check for a file
 # Installation integrity check
 
-# Check for our config directory
-if [ ! -d $CONFIG ]; then
-	failed "configuration directory not found!"
-	exit 1
-fi
+have_env HOST $HOST
+have_env STATE $STATE
+have_env CONFIG $CONFIG
+have_env INSTALL $INSTALL
 
-# Check the script installation
-if [ ! -x $INSTALL/drbd_commun ]; then
-	failed "drbd script functions not found!"
-	exit 1
-fi
+have_dir $CONFIG
+have_file $INSTALL/drbd_commun
+have_command drbdsetup fuser lsmod modprobe
 
-# Check the program(s) installation
-if [ ! -x /usr/sbin/drbdsetup ]; then
-	failed "drbdsetup not found!"
-	exit 1
-fi
+# RETVAL will work as a "stuck bit" for any error. The construct
+# RV=$?
+# [ $RETVAL -eq 0 ] && RETVAL=$RV
+# allows us to have it stuck at 1 when some error occur, even if
+# subsequent operations don't fail. Using $RV prevents us from getting
+# the exit value of [ ... ]. That was a dumb one... :)
 
-# Check for fuser command
-if [ ! `which fuser 2>/dev/null` ]; then
-	failed "$0 needs the fuser command"
-	exit 1
-fi
-				
+RETVAL=0        # this means there were errors
+RV=0            # this means there were errors in the current device
 
+if [ "$2" != "" ]; then
+	OPTION=$1
+	RESOURCE=$2
+else
+	OPTION=$1
+	RESOURCE=""
+fi
diff --git a/drbd/scripts/drbdc b/drbd/scripts/drbdc
--- a/drbd/scripts/drbdc
+++ b/drbd/scripts/drbdc
@@ -19,8 +19,9 @@
 # Some ideas and inspiration from Joe Hartley <jh@brainiac.com>
 
 INSTALL="/etc/ha.d/resource.d"
-
 . $INSTALL/drbd_commun
+
+RETVAL=0
 
 # Check if the node is primary
 # Param : The resource
@@ -58,7 +59,7 @@ rudeUnMount()
 	MOUNTED=$?
 		
 	if [ $MOUNTED -eq 1 ]; then
-		$0 $1 umount
+		$0 umount $1
 
 		isMounted $1
 		MOUNTED=$?
@@ -66,7 +67,7 @@ rudeUnMount()
 		if [ $MOUNTED -eq 1 ]; then
 			fuser -km $2
 			sleep 1
-			$0 $1 umount
+			$0 umount $1
 		fi
  
 		isMounted $1
@@ -75,7 +76,7 @@ rudeUnMount()
 		if [ $MOUNTED -eq 1 ]; then
 			fuser -km -9 $2
 			sleep 1
-			$0 $1 umount
+			$0 umount $1
 		fi
 
 		isMounted $1
@@ -85,31 +86,16 @@ rudeUnMount()
 	return $MOUNTED
 }
 
-runForAll ()
-{
-	pushd . > /dev/null
-		cd $CONFIG
-		DEVICES=`ls drbd[0-9] | sort 2>/dev/null`
-	popd > /dev/null
-
-	for D in $DEVICES; do
-		for RUN in $*; do
-			$0 $D $RUN
-		done
-	done
-}
-
 # See how we were called.
 case "$1" in
 	primary)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll primary
 			exit $RETVAL
 		fi
 		
-		setLocal $RESOURCE
+		setLocal $CONFIG $RESOURCE
+
 		isMounted $RESOURCE
 
 		if [ $? -eq 1 ]; then
@@ -118,20 +104,18 @@ case "$1" in
 		fi
 
 		action "Becoming primary on DRBD resource $RESOURCE" \
-			/usr/sbin/drbdsetup $LOCAL_DEVICE PRI
+			drbdsetup $LOCAL_DEVICE PRI
 		RV=$?
 		[ $RETVAL -eq 0 ] && RETVAL=$RV
 		;;
 
 	secondary)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll secondary
 			exit $RETVAL
 		fi
 		
-		setLocal $RESOURCE
+		setLocal $CONFIG $RESOURCE
 		isMounted $RESOURCE
 
 		if [ $? -eq 1 ]; then
@@ -140,36 +124,35 @@ case "$1" in
 		fi
 
 		action "Becoming secondary on DRBD resource $RESOURCE" \
-			/usr/sbin/drbdsetup $LOCAL_DEVICE SEC
+			drbdsetup $LOCAL_DEVICE SEC
 		RV=$?
 		[ $RETVAL -eq 0 ] && RETVAL=$RV
 		;;
 
 	master)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll master
 			exit $RETVAL
 		fi
 
+		setLocal $CONFIG $RESOURCE
+
 		isPrimary $RESOURCE
 		PRIMARY=$?
 
-		setLocal $RESOURCE
 		isMounted $RESOURCE
 		MOUNTED=$?
 
 		if [ $PRIMARY -eq 0 -a $MOUNTED -eq 0 ]; then
-			$0 $RESOURCE primary && 
-			$0 $RESOURCE fsck && 
-			$0 $RESOURCE mount
+			$0 primary $RESOURCE && 
+			$0 fsck $RESOURCE && 
+			$0 mount $RESOURCE 
 			RV=$?
 			[ $RETVAL -eq 0 ] && RETVAL=$RV
 		fi
 		if [ $PRIMARY -eq 1 -a $MOUNTED -eq 0 ]; then
-			$0 $RESOURCE fsck && 
-			$0 $RESOURCE mount
+			$0 fsck $RESOURCE && 
+			$0 mount $RESOURCE 
 			RV=$? 
 			[ $RETVAL -eq 0 ] && RETVAL=$RV
 		fi
@@ -178,26 +161,24 @@ case "$1" in
 			RV=$? 
 			[ $RETVAL -eq 0 ] && RETVAL=$RV
 		fi
+		if [ $RETVAL -eq 0 -a $PRIMARY -eq 1 ]; then
+			setMasterBoot $RESOURCE
+		fi
 		if [ $RETVAL -ne 0 -a $PRIMARY -eq 0 ]; then
-			$0 $RESOURCE secondary 
+			$0 secondary $RESOURCE
 			RV=$? 
 			[ $RETVAL -eq 0 ] && RETVAL=$RV
-		fi
-
-		if [ $RETVAL -eq 0 ]; then
-			setMasterBoot $RESOURCE
 		fi
 		;;
 
 	slave)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll slave
 			exit $RETVAL
 		fi
 
-		setLocal $RESOURCE
+		setLocal $CONFIG $RESOURCE
+
 		isMounted $RESOURCE
 		MOUNTED=$?
 
@@ -208,23 +189,29 @@ case "$1" in
 
 		# Only become secondary if umount succed
 		if [ $RETVAL -eq 0 ]; then
-			$0 $RESOURCE secondary
-			setLocal $RESOURCE
-			drbdsetup $LOCAL_DEVICE wait
+			$0 secondary $RESOURCE 
 			RETVAL=$?
-			setSlaveBoot $RESOURCE
+			if [ "$RETVAL" -eq 0 ]; then
+				setSlaveBoot $RESOURCE
+			fi
 		fi
 		;;
 
 	mount)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll mount
 			exit $RETVAL
 		fi
 
-		setLocal $RESOURCE
+		setLocal $CONFIG $RESOURCE
+
+		isPrimary $RESOURCE
+		PRIMARY=$?
+
+		if [ $PRIMARY -eq 0 ]; then
+			failure "Can not mount $LOCAL_DEVICE as $LOCAL_NODE is slave"
+			exit 1
+		fi
 
 		isMounted $RESOURCE
 		MOUNTED=$?
@@ -241,14 +228,20 @@ case "$1" in
 		;;
 
 	umount)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll umount
 			exit $RETVAL
 		fi
 
-		setLocal $RESOURCE
+		setLocal $CONFIG $RESOURCE
+
+		isPrimary $RESOURCE
+		PRIMARY=$?
+
+		if [ $PRIMARY -eq 0 ]; then
+			failure "Can not mount $LOCAL_DEVICE as $LOCAL_NODE is slave"
+			exit 1
+		fi
 
 		isMounted $RESOURCE
 		MOUNTED=$?
@@ -266,19 +259,26 @@ case "$1" in
 		;;
 
 	fsck)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll fsck
 			exit $RETVAL
 		fi
 
-		setLocal $RESOURCE
+		setLocal $CONFIG $RESOURCE
+
+		isPrimary $RESOURCE
+		PRIMARY=$?
+
+		if [ "$PRIMARY" -eq 1 ]; then
+			failed "Can not perform fsck on secondary $RESOURCE "
+			exit 1
+		fi
+
 		isMounted $RESOURCE
 		MOUNTED=$?
 
 		if [ $MOUNTED -eq 1 ]; then
-			$0 $RESOURCE umount 
+			$0 umount $RESOURCE 
 			RV=$? 
 			[ $RETVAL -eq 0 ] && RETVAL=$RV
 		fi
@@ -288,62 +288,49 @@ case "$1" in
 			exit 1
 		fi
 
-		isPrimary $RESOURCE
-		if [ $? -eq 1 ]; then
-			echo -n "performing fsck on $RESOURCE " 
-			$LOCAL_FSCK $LOCAL_DEVICE > /dev/null 2>/dev/null
-			RV=$?
-			[ $RV -eq 0 -o $RV -eq 1 ] && RETVAL=0
-			[ $RETVAL -eq 0 ] && success || failure
-			echo
-		else
-			failed "Can not perform fsck on secondary $RESOURCE "
-			RETVAL=1
-		fi
+		echo -n "performing fsck on $RESOURCE " 
+		$LOCAL_FSCK $LOCAL_DEVICE > /dev/null 2>/dev/null
+		RV=$?
+		[ $RV -eq 0 -o $RV -eq 1 ] && RETVAL=0
+		[ $RETVAL -eq 0 ] && success || failure
+		echo
 
 		if [ $MOUNTED -eq 1 ]; then 
-			$0 $RESOURCE mount
+			$0 mount $RESOURCE
 			RV=$?
 			[ $RV -eq 0 ] && RETVAL=$RV
 		fi
 		;;	
 
 	resync)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll resync
 			exit $RETVAL
 		fi
 
+		setLocal $CONFIG $RESOURCE
+
 		isPrimary
 		PRIMARY=$?
 
-		if [ $PRIMARY -eq 0 ]; then
-			# TODO:DRDB sometimes lies about its connection status !!
-			isConnected
-			CONNECTED=$?
-
-			if [ $CONNECTED -eq 1 ]; then
-				setLocal $RESOURCE
-
-				rudeUnMount $RESOURCE $LOCAL_DEVICE
-				MOUNTED=$?
-
-				if [ $MOUNTED -eq 0 ]; then
-					drbdsetup $LOCAL_DEVICE repl
-					RETVAL=$?
-				else
-					failed "unmount failed, you must have a SERIOUS problem"
-				fi
-			else
-				failed "The node is not connected to the primary"
-				RETVAL=1
-			fi
-		else
-			failed "$LOCAL_DEVICE is primary. The command must be run from a connected slave"
-			RETVAL=1
+		if [ $PRIMARY -eq 1 ]; then
+			failed "resync must be run from a (connected) slave"
+			exit 1
 		fi
+
+		# TODO:DRDB sometimes lies about its connection status !!
+		# See how to understand the slave/?? line 
+
+		isConnected
+		CONNECTED=$?
+
+		if [ $CONNECTED -eq 0 ]; then
+			failed "node not connected to the primary"
+			exit 1
+		fi
+
+		drbdsetup $LOCAL_DEVICE repl
+		RETVAL=$?
 		;;
 		
 	proc)
@@ -356,39 +343,50 @@ case "$1" in
 		;;
 
 	status)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll status
 			exit $RETVAL
 		fi
 
 		if [ -r /proc/drbd ]; then
+			setLocal $CONFIG $RESOURCE
+
 			isPrimary $RESOURCE
 			PRIMARY=$?
 
-			setLocal $RESOURCE
 			isMounted $RESOURCE
 			MOUNTED=$?
-			
-			if [ $PRIMARY -eq 1 ]; then
+
+			isConnected $RESOURCE
+			CONNECTED=$?
+
+			isSyncing $RESOURCE
+			SYNC=$?
+
+			haveRemotePrimary $RESOURCE
+			RPRIMARY=$?
+
+			haveRemoteSecondary $RESOURCE
+			RSECONDARY=$?
+
+			if [ "$SYNC" -eq 1 ]; then
+				echo "not ready"
+			elif [ $PRIMARY -eq 1 ]; then
 				if [ $MOUNTED -eq 1 ]; then
-					echo "Running"
+					echo "running"
 				else
 					echo "Failed"
 				fi
 			else
-				echo "Ready"
+				echo "ready"
 			fi
 		else
-			echo "Failed"
+			echo "failed"
 		fi
 		;;
 	
 	running)
-		if [ -n "$RESOURCE" ]; then
-			. $CONFIG/$RESOURCE
-		else
+		if [ -z "$RESOURCE" ]; then
 			runForAll running
 			exit $RETVAL
 		fi
@@ -415,14 +413,14 @@ case "$1" in
 
 		isMasterBoot $RESOURCE
 		if [ $? -eq 1 ]; then
-			succed "Master"
+			echo "Master"
 		else
-			succed "Slave"
+			echo "Slave"
 		fi
 		;;
 
 	help)
-		echo "Usage: $0 [resource] [command]"
+		echo "Usage: $0 [command] [resource]"
 		echo
 		echo "command can be :"
 		echo
