ci: fix CI build for DRBD 10
DRBD 10 excludes the release part from the "REL_VERSION", which is the
version used in the name of the source tarball. Adjust the CI build to
match.

These changes have been made in such a way that they can be used largely
the same on the drbd-9.0 branch to reduce merging effort.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,7 +1,7 @@
 variables:
   VIRTER_VERSION: v0.6.0
   VMSHED_VERSION: v0.6.0
-  BUILD_HELPERS_VERSION: c0d39c0e5a2235262f21d072c4bf3b2dd62b2040
+  BUILD_HELPERS_VERSION: 378ab075793ec9fef875b67ee1c4dc53a681d49a
   # we have to change the way GitLab CI clones the repository.
   # by default, it is shallow, which gives us a wrong commit count when
   # we do `git rev-list --count origin/master` below.
@@ -23,26 +23,27 @@ stages:
       drbd_build () {
         local version="$1"
         local release="$2"
+        local rel_version="$3"
 
         mkdir -p drbd-test-bundle
         curl -sSL $LINBIT_REGISTRY_URL/repository/test-suite/drbd-test-bundle.tgz | tar -C drbd-test-bundle -xvzf -
 
-        drbd_dummy_release "$version" "$release"
-        make FORCE=1 PRESERVE_DEBIAN=1 REL_VERSION="$version-$release" tarball
+        drbd_dummy_release "$version" "$release" "$rel_version"
+        make FORCE=1 PRESERVE_DEBIAN=1 REL_VERSION="$rel_version" tarball
 
         curl -isSf -u $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file drbd-*.tar.gz $LINBIT_REGISTRY_URL/repository/lbbuild-upstream/
 
         META_JSON=$(rq -t < drbd-test-bundle/virter/vms.toml | jq -r '.vms[].metadata')
         echo "$META_JSON" | jq -r '. | "-d " + .BuildDistribution + " -k " + .KernelRelease' | parallel --colsep ' ' -k -j24 \
-          lbbuildctl build drbd --arch amd64 --ci -v "${version}-${release}" --compat-only -l \
+          lbbuildctl build drbd --arch amd64 --ci -v "$rel_version" --compat-only -l \
             -e LINBIT_REGISTRY_USER=$LINBIT_REGISTRY_USER \
             -e LINBIT_REGISTRY_PASSWORD=$LINBIT_REGISTRY_PASSWORD \
             -e LINBIT_REGISTRY_URL=$LINBIT_REGISTRY_URL \
             {}
 
         pushd drbd/drbd-kernel-compat
-        ASSETS_JSON=$(curl -ksSL "$LINBIT_REGISTRY_URL/service/rest/v1/search/assets?repository=drbd-compat&group=/${version}-${release}")
-        test $(echo "$ASSETS_JSON" | jq '.items | length') -ne 0 || (echo "ERROR No nexus assets found for drbd version ${version}-${release}"; exit 1)
+        ASSETS_JSON=$(curl -ksSL "$LINBIT_REGISTRY_URL/service/rest/v1/search/assets?repository=drbd-compat&group=/$rel_version")
+        test $(echo "$ASSETS_JSON" | jq '.items | length') -ne 0 || (echo "ERROR No nexus assets found for drbd version $rel_version"; exit 1)
         URLS=$(echo "$ASSETS_JSON" | jq -r '.items[].downloadUrl')
         FILES=$(echo "$URLS" | xargs basename -a)
         echo "$URLS" | while read url; do
@@ -52,12 +53,12 @@ stages:
         popd
 
         make -j $(nproc) -C drbd compat
-        make FORCE=1 PRESERVE_DEBIAN=1 REL_VERSION="$version-$release" tarball
+        make FORCE=1 PRESERVE_DEBIAN=1 REL_VERSION="$rel_version" tarball
         curl -isSf -u $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file drbd-*.tar.gz $LINBIT_REGISTRY_URL/repository/lbbuild-upstream/
 
         META_JSON=$(rq -t < drbd-test-bundle/virter/vms.toml | jq -r '.vms[].metadata')
         echo "$META_JSON" | jq -r '. | "-d " + .BuildDistribution + " -k " + .KernelRelease' | parallel --colsep ' ' -k -j24 \
-          lbbuildctl build drbd --arch amd64 --ci -v "${version}-${release}" -l \
+          lbbuildctl build drbd --arch amd64 --ci -v "$rel_version" -l \
             -e LINBIT_REGISTRY_USER=$LINBIT_REGISTRY_USER \
             -e LINBIT_REGISTRY_PASSWORD=$LINBIT_REGISTRY_PASSWORD \
             -e LINBIT_REGISTRY_URL=$LINBIT_REGISTRY_URL \
@@ -78,7 +79,7 @@ build:
   script:
     - DRBD_VERSION=10.0.0.$CI_COMMIT_SHA
     - echo DRBD_VERSION=$DRBD_VERSION >> build.env
-    - drbd_build $DRBD_VERSION 1
+    - drbd_build $DRBD_VERSION 1 $DRBD_VERSION
   artifacts:
     reports:
       dotenv: build.env
@@ -96,7 +97,7 @@ build-latest:
   script:
     - DRBD_VERSION=10.0.0.latest
     - DRBD_RELEASE=$(git rev-list --count origin/master)
-    - drbd_build $DRBD_VERSION $DRBD_RELEASE
+    - drbd_build $DRBD_VERSION $DRBD_RELEASE $DRBD_VERSION
 
 
 test:
