r802: Lars' "Kleinigkeiten"

diff --git a/drbd/Makefile b/drbd/Makefile
--- a/drbd/Makefile
+++ b/drbd/Makefile
@@ -42,24 +42,25 @@ distclean:
 uninstall:
 	@ set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i uninstall; done
 
+DIST_VERSION=$(subst -,_,$(REL_VERSION))
 check_changelogs_up2date:
 	@ up2date=true; \
-	if ! grep "^Version: $(REL_VERSION)" >/dev/null 2>&1 drbd.spec; \
+	if ! grep "^Version: $(DIST_VERSION)" >/dev/null 2>&1 drbd.spec; \
 	then \
-	   echo "You need to update the Version: tag in drbd.spec"; \
+	   echo "You need to update the Version: tag in drbd.spec to $(DIST_VERSION)"; \
 	   up2date=false; fi; \
 	if ! sed -e '0,/^%changelog/d' drbd.spec \
-	   | grep "^- drbd ($(REL_VERSION)-" >/dev/null 2>&1 ; \
+	   | grep "^- drbd ($(DIST_VERSION)-" >/dev/null 2>&1 ; \
 	then \
-	   echo "You need to update the %changelog in drbd.spec"; \
+	   echo "You need to update the %changelog in drbd.spec, $(DIST_VERSION) missing"; \
 	   up2date=false; fi; \
-	if ! grep "^drbd ($(REL_VERSION)-" >/dev/null 2>&1 debian/changelog; \
+	if ! grep "^drbd ($(DIST_VERSION)-" >/dev/null 2>&1 debian/changelog; \
 	then \
-	   echo "You need to update debian/changelog"; \
+	   echo "You need to update debian/changelog, $(DIST_VERSION) missing"; \
 	   up2date=false; fi ; \
-	if ! grep "^drbd_$(REL_VERSION)-" >/dev/null 2>&1 debian/files; \
+	if ! grep "^drbd_$(DIST_VERSION)-" >/dev/null 2>&1 debian/files; \
 	then \
-	   echo "You need to update debian/files"; \
+	   echo "You need to update debian/files, $(DIST_VERSION) missing"; \
 	   up2date=false; fi ; \
 	$$up2date
 
@@ -67,15 +68,15 @@ check_changelogs_up2date:
 #tgz: check_changelogs_up2date
 tgz:
 	cd scripts; ln -sf drbd datadisk
-	rm -f drbd-$(REL_VERSION)
-	ln -s . drbd-$(REL_VERSION)
-	tar -czvf drbd-$(REL_VERSION).tar.gz \
-	--exclude drbd-$(REL_VERSION)/drbd-$(REL_VERSION) \
+	rm -f drbd-$(DIST_VERSION)
+	ln -s . drbd-$(DIST_VERSION)
+	tar -czvf drbd-$(DIST_VERSION).tar.gz \
+	--exclude drbd-$(DIST_VERSION)/drbd-$(DIST_VERSION) \
 	--exclude "*.o"  --exclude CVS --exclude ".*" \
 	--exclude "*~"  --exclude "*.tar.gz" \
 	--exclude drbdsetup --exclude dm --exclude config \
-	--exclude "report*" drbd-$(REL_VERSION)/*
-	rm drbd-$(REL_VERSION)
+	--exclude "report*" drbd-$(DIST_VERSION)/*
+	rm drbd-$(DIST_VERSION)
 
 # maybe dist/RPMS/$(ARCH) instead of i386 ?
 rpm: tgz
@@ -83,11 +84,12 @@ rpm: tgz
 	         dist/RPMS/i386 \
 	         dist/SPECS \
 	         dist/SOURCES \
-	         dist/install \
-	         dist/SRPMS
-	[ -h dist/SOURCES/drbd-$(REL_VERSION).tar.gz ] || \
-	  $(LN_S) $(PWD)/drbd-$(REL_VERSION).tar.gz \
-	          $(PWD)/dist/SOURCES/drbd-$(REL_VERSION).tar.gz
+	         dist/SRPMS \
+	         dist/TMP \
+	         dist/install
+	[ -h dist/SOURCES/drbd-$(DIST_VERSION).tar.gz ] || \
+	  $(LN_S) $(PWD)/drbd-$(DIST_VERSION).tar.gz \
+	          $(PWD)/dist/SOURCES/drbd-$(DIST_VERSION).tar.gz
 	[ -f dist/SPECS/drbd.spec ] || \
 	  sed -e 's/^\(Packager:\).*/\1 ${USER}@${HOSTNAME}/;' drbd.spec \
 	  > dist/SPECS/drbd.spec
